config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'populate_carts#index'
  resources :orders, only: %i[index update show create]
  resources :carts, only: %i[create index]
  resources :inline_items, only: %i[update create destroy]
  resources :items, only: %i[show index create update]
  resources :categories, only: %i[index create]
  resources :populate_carts, only: [:index]
  resources :search, only: [:index]

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/controllers/search_controller.rb
# frozen_string_literal: true

# search controller
class SearchController < ApplicationController
  def index
    @query = Item.permited_items.ransack(params[:q])
    # it will return all of the search reslts
    @items = @query.result(distinct: true)
    @searched_category = params[:selected_category]
    @searched_category = '' if @searched_category.nil?
  end
end

app/helpers/search_helper.rb
# frozen_string_literal: true

# search helper
module SearchHelper
end

app/views/search/_form.html.erb
<%= search_form_for(@query, url: search_index_path, method: :get,class:'form-inline my-2 my-lg-0 ') do |f| %>
    <%= f.search_field :title_i_cont_any, placeholder: "Search...", class: "form-control mr-sm-2"%>
    <%= f.submit "Search!", class: "btn btn-outline-success my-2 my-sm-0" %>
    <%=select_tag 'selected_category', options_for_select(Category.all.collect{ |u| [u.name] }),{include_blank: "select category"} %>
<% end %>

app/views/search/index.html.erb
<h1 class="text-center">Result</h1>
<div class="container ">
<table class="table table-dark table-striped">
  <thead>
    <tr>
    <th><%= sort_link(@query, :title, "Title", default_order: :asc) %></th>
    <th><%= sort_link(@query, :description, "Item Description"  )%></th>
    <th><%= sort_link(@query, :price, "Item Price"  )%></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item|%>
      <%if (@searched_category.in?(item.categories.pluck(:name)) || @searched_category=="") %>
        <tr>
          <td><%= link_to item.title, item%></td>
          <td><%= item.description.truncate_words(25)%></td>
          <td><%= item.price%></td>
        </tr>
      <%end%>
    <%end%>
  </tbody>
</table>
</div>