config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'populate_carts#index'
  resources :orders, only: %i[index update show create]
  resources :carts, only: %i[create index]
  resources :inline_items, only: %i[update create destroy]
  resources :items, only: %i[show index create update]
  resources :categories, only: %i[index create]
  resources :populate_carts, only: [:index]
  resources :search, only: [:index]

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Dinner Dash', items_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%if current_user%>
        <li style="color:green;font-weight: bold;" class="mt-2 nav-item">
          <%=current_user.display_name || current_user.full_name%>
        </li>
        <%end%>
        <%if current_user%>
        <li style="color:white;font-weight: bold;" class="mt-2 nav-item">
          <%=current_user.role%>
        </li>
        <%end%>

        <%if !current_user || current_user.user?%>
        <li class="nav-item">
          <%= link_to "My Cart", carts_path, class:"nav-link"%>
        </li>
        <%end%>
        <%if current_user%>
        <%if current_user.user?%>
        <li class="nav-item">
          <%= link_to "My Orders", orders_path, class:"nav-link"%>
        </li>
        <%end%>
        <%end%>
        <%if current_user%>
        <%if current_user.admin?%>
        <li class="nav-item">
          <%= link_to "All Orders", orders_path, class:"nav-link"%>
        </li>
        <%end%>
        <%end%>
        <li class="nav-item">
          <%= link_to "Items", items_path, class:"nav-link"%>
        </li>
        <%if current_user%>
        <%if current_user.admin?%>
        <li class="nav-item">
          <%= link_to "Category", categories_path, class:"nav-link"%>
        </li>
        <%end%>
        <%end%>
        <%if current_user%>
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete ,class:"nav-link"%>
        </li>
        <%else%>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class:"nav-link"%>
        </li>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class:"nav-link"%>
        </li>
        <%end%>
        <li>
          <%= render 'search/form' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Dinner Dash</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
     <script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </head>
  <body>
  <%= render partial: "layouts/header" %>
  <div class="container">
    <div id="flash">
      <% if notice.present? %>
        <%= render partial: "shared/notice_banner" %>
      <% end %>
    </div>
  <p class="alert"><%= alert %></p>
   <%= yield %>
   </div>
  </body>
</html>